version: "3"
services:
  golang:
    privileged: true
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./:/go/src/app
  nginx:
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
    volumes:
      - ./public:/usr/share/nginx/html